import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-brand-green': '#468432',
  '--slot4-brand-lime': '#9AD872',
  '--slot4-brand-cream': '#FFEF91',
  '--slot4-brand-orange': '#FFA02E',
  '--slot4-page-bg': '#0b0f0a',
  '--slot4-page-text': '#f7f4de',
  '--slot4-panel-bg': '#141a12',
  '--slot4-surface-bg': '#10150f',
  '--slot4-muted-text': '#b8c0a7',
  '--slot4-soft-muted-text': '#89917d',
  '--slot4-accent': 'var(--slot4-brand-lime)',
  '--slot4-accent-fill': 'var(--slot4-brand-green)',
  '--slot4-accent-soft': 'rgba(154, 216, 114, 0.12)',
  '--slot4-on-accent': '#081006',
  '--slot4-dark-bg': '#050805',
  '--slot4-dark-text': '#fff9dc',
  '--slot4-media-bg': '#1a2117',
  '--slot4-cream': 'var(--slot4-brand-cream)',
  '--slot4-warm': '#121710',
  '--slot4-lavender': '#121710',
  '--slot4-gray': '#161d14',
  '--slot4-body-gradient': 'radial-gradient(circle at top, rgba(154, 216, 114, 0.1), transparent 28%), radial-gradient(circle at 85% 0%, rgba(255, 160, 46, 0.08), transparent 20%), linear-gradient(180deg, #0b0f0a 0%, #0f140d 35%, #0b0f0a 100%)',
  '--editable-page-bg': '#0b0f0a',
  '--editable-page-text': '#f7f4de',
  '--editable-container': '1460px',
  '--editable-border': 'rgba(255,239,145,0.12)',
  '--editable-nav-bg': 'rgba(8,12,8,0.94)',
  '--editable-nav-text': '#f7f4de',
  '--editable-nav-active': 'var(--slot4-brand-lime)',
  '--editable-nav-active-text': '#081006',
  '--editable-cta-bg': 'var(--slot4-brand-orange)',
  '--editable-cta-text': '#081006',
  '--editable-search-bg': '#10150f',
  '--editable-footer-bg': '#080b07',
  '--editable-footer-text': '#f7f4de',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_55px_rgba(0,0,0,0.24)]',
  shadowStrong: 'shadow-[0_28px_90px_rgba(0,0,0,0.34)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(4,7,4,0.02),rgba(4,7,4,0.88))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-8 xl:grid-cols-[1.25fr_0.75fr]',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[220px] shrink-0 snap-start sm:w-[260px]',
  },
  type: {
    eyebrow: 'text-[11px] font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-semibold leading-[1.02] tracking-[-0.04em] sm:text-5xl lg:text-[4rem]',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.03em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[2rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--editable-cta-bg)] px-6 py-3 text-sm font-semibold text-[var(--editable-cta-text)] transition duration-300 hover:-translate-y-0.5 hover:brightness-105',
    secondary: 'inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)]',
    accent: 'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:brightness-110',
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.5rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_22px_65px_rgba(0,0,0,0.3)]',
    fade: 'transition duration-300 hover:opacity-85',
  },
} as const

export const aiLayoutRules = [
  'Keep all visual changes inside src/editable only.',
  'Prefer marketplace-style layouts with search-first hierarchy and mixed card sizes.',
  'Use the shared CSS variables in editableRootStyle for global color changes.',
  'Keep dynamic post fetching intact and always render real post data with fallbacks.',
  'Use postHref() or the existing task route pattern for links so route support stays intact.',
]
